from pathlib import Path
from datetime import datetime

from pptx import Presentation
from pptx.util import Inches, Pt


class PresentationService:

    def __init__(self):

        self.output_dir = Path("outputs")

        self.output_dir.mkdir(exist_ok=True)

    def create_presentation(
        self,
        title: str,
        slides: list[dict]
    ):

        prs = Presentation()

        # ---------- Title Slide ----------

        title_layout = prs.slide_layouts[0]

        slide = prs.slides.add_slide(title_layout)

        slide.shapes.title.text = title

        slide.placeholders[1].text = (
            "Generated by AI Productivity Agent"
        )

        # ---------- Content Slides ----------

        bullet_layout = prs.slide_layouts[1]

        

        for slide_data in slides:

            slide_obj = prs.slides.add_slide(
                bullet_layout
            )

            slide_obj.shapes.title.text = slide_data["title"]

            text_frame = (
                slide_obj.placeholders[1]
                .text_frame
            )

            text_frame.clear()

            for bullet in slide_data["bullets"]:

                paragraph = text_frame.add_paragraph()

                paragraph.text = bullet

                paragraph.level = 0

                paragraph.font.size = Pt(22)

        timestamp = datetime.now().strftime(
            "%Y%m%d_%H%M%S"
        )

        filename = (
            f"{title.replace(' ','_')}_{timestamp}.pptx"
        )

        filepath = self.output_dir / filename

        prs.save(filepath)

        return str(filepath)